version: '3'

services:
  dalai:
    container_name: DalAI
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LLAMA_VERSION= # add the module version here (e.g. 7B)
        - ALPACA_VERSION= # add the module version here (e.g. 7B)
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dalai

networks:
  dalai:
    driver: bridge