version: '3'

services:
  dalai:
    container_name: DalAI
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - dalai

networks:
  dalai:
    driver: bridge